### ISSUE TITLE
commands print

### ISSUE THREAD

**Issue by niodamian** [kibook/logmanager#2]
can i print the commands separate ? 
like i wanna /ooc etc

**Comment by kibook** [comment]
I don't know if there is any kind of event to tap into that is triggered when any command is executed anywhere, but I made [a branch of my modified chat resource](https://github.com/kibook/PoodleChat/tree/logmanager) that logs whenever a command is executed through the chat.

For other commands, you may have to do something similar and add a call to `exports.logmanager:log` in the resource that handles the command in order to add an entry to the log when that command is executed.
